<?php

return [
    'game_type' => [
        '1' => 'Liên quân mobile (Quân huy)',
        '2' => 'Freefire (kim cương)',
        '3' => 'Liên minh',
        '4' => 'Blade an Soul',
        '5' => 'Âm dương sư',
        '6' => 'Fifa online 4',
        '7' => 'Fifa online 4 mobile',
        '8' => 'Pubg mobile',
        '9' => 'Genshin Impact',
        '10' => 'BlockMango',
        '11' => 'Ninjaxu school',
        '12' => 'Ngọc rồng (Ngọc)',
        '13' => 'Roblox',
        '14' => 'Ngọc rồng (Vàng)',

    ],
    'game_type_map' => [
        '1' => 'lienquan',
        '2' => 'freefire',
        '3' => 'lienminh',
        '4' => 'bns',
        '5' => 'ads',
        '6' => 'fo4',
        '7' => 'fo4m',
        '8' => 'pubgm',
        '9' => 'genesis_crystal',
        '10' => 'blockmango',
        '11' => 'ninjaxu',
        '12' => 'nrogem',
        '13' => 'roblox_buyserver',
        '14' => 'nrocoin',
    ],
    'game_type_value' => [
        '1' => 'QUÂN HUY',
        '2' => 'KC',
        '3' => 'RP',
        '4' => 'VÀNG',
        '5' => 'ads',
        '6' => 'fo4',
        '7' => 'fo4m',
        '8' => 'UC',
        '9' => 'Genesis Crystal',
        '10' => 'GCUBE',
        '11' => 'XU',
        '12' => 'HỒNG NGỌC',
        '13' => 'ROBUX',
        '14' => 'VÀNG',
    ],
    'withdraw_status' => [
        '0'=>'Chờ xử lý',
        '1'=>'Hoàn thành',
        '2'=>'Thanh toán lỗi',
        '3'=>'Giao dịch lỗi (xem tiến độ)'
    ],
];
